### PR TITLE
Gradle build quoting

### PR DESCRIPTION
**Pull request by binkley**
1. Use double quote marks throughout (note: unlike most Gradle projects I look at, yours is already consistent in use of single quotes, rather than a mish-mash of single and double quotes)
2. The Gradle Kotlin DSL does not support single quote marks

@charleskorn You might think about if using the Kotlin DSL for Gradle should be something going foward.  If that makes sense to you (and I see you are thinking about it, _ie_, `updateInfoUpload.gradle.kts`), then updating the build script quoting is a first step.

See successful GitHub actions for this commit in a fork: https://github.com/binkley/batect/actions/runs/347819118

The key step in creating this commit: `find -name build.gradle -o -name settings.gradle | xargs sed -i "s/'/\"/g"` -- yay for UNIX command line :)

### CODE REVIEW

**Comment by binkley** [comment]
I have no idea about the change in code coverage.  I only edited the build scripts.  I'll investigate.

**Comment by charleskorn** [comment]
This looks great to me, thanks @binkley 

Do you know if there's a way to configure Spotless to catch this in the future? That way it will remain consistent forever

**Comment by binkley** [comment]
re: Spotless.  I did some cursory searches through the Spotless codebase, and this does not appear for me to be something they have considered.

OTOH, once build scripts are in Kotlin, the compiler will enforce this.  So a contributor rule might be: Only provide Gradle scripts using the Kotlin DSL.

**Comment by charleskorn** [comment]
> once build scripts are in Kotlin, the compiler will enforce this. So a contributor rule might be: Only provide Gradle scripts using the Kotlin DSL.

Seems pretty sensible to me.

**Pull request merged**
