### PR TITLE
Configure the "versions" Gradle plugin to not lists RCs

### PR DESCRIPTION
**Pull request by sschuberth**
If you agree with this configuration, I can submit another PR with some dependency updates 😸

### CODE REVIEW

**Comment by charleskorn** [comment]
Looks great, thanks @sschuberth.

In terms of updates for other packages, these _should_ be handled by Renovate automatically. If these updates aren't being handled by Renovate, it would be great to understand why it isn't updating them, rather than having to manually update them.

**Comment by charleskorn** [comment]
(I'll merge this as soon as the build passes.)

**Comment by sschuberth** [comment]
I just ran `./gradlew depUp` after the merge, and the *versions* plugin reports:

```
The following dependencies have later milestone versions:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin [0.38.0 -> 0.39.0]
 - com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin [6.1.0 -> 7.0.0]
 - org.jetbrains.kotlin:kotlin-bom [1.5.21 -> 1.5.30]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-reflect [1.5.21 -> 1.5.30]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-stdlib-jdk8 [1.5.21 -> 1.5.30]
     https://kotlinlang.org/
 - org.junit.platform:junit-platform-engine [1.7.1 -> 1.7.2]
     https://junit.org/junit5/
 - org.mockito:mockito-core [3.7.7 -> 3.12.4]
     https://github.com/mockito/mockito
```

My guess is that Renovate does not cover Gradle plugins, and neither does is cover the Kotlin version implied by Gradle. And mockito, well, no idea 😀

**Comment by charleskorn** [comment]
The Kotlin upgrade should be covered by #976. And the other plugins have been upgraded by Renovate in the past (eg. #815 or #676), so not quite sure what's going on there, I'll take a look.

**Comment by charleskorn** [comment]
I think this is fixed now - Renovate is now successfully generating PRs for those dependencies now. Thanks for spotting this and letting me know.

**Comment by sschuberth** [comment]
I'm happy to this fixed now, but esp. when looking at https://github.com/batect/batect/commit/5cb74f7bb955cbb0b152eebd04ec7f665549e796 I wonder whether using Renovate is really worth it, as with the *versions* plugin there's already another mechanism to check for dependency updates which fully understands Gradle's internals.

If you're looking for the convenience to also perform the actual update automatically, maybe it's worth looking at https://github.com/jmfayard/refreshVersions (and running that in a scheduled GitHub Action to create PRs).

**Comment by sschuberth** [comment]
> and running that in a scheduled GitHub Action to create PRs

Looks like there already is something like that at https://github.com/DanySK/upgradle.

**Comment by charleskorn** [comment]
The advantage of Renovate is that it can cover much more than just Maven dependencies - it also does Docker images out of the box, and I've configured it to cover a bunch of other more obscure cases (eg. dependencies within Dockerfiles, instances where we're referencing dependencies in a non-standard way or using non-Maven dependencies).

I'm hoping that with the move to version catalogs, this will vastly simplify things, at least in the Gradle space.

**Pull request merged**
