### PR TITLE
Add `-h` as an alias for `--help`

### PR DESCRIPTION
**Pull request by binkley**
Users typically expect to run `$foo_program -h` for help.  The GNU
standard on command-line options only mentions `--help` and `--version`;
a random survey of typical programs show the large majority using `-h`
as an alias for `--help` (OS-provided, or OSS). There are some legacy
programs (going back to the 1970s and 1980s) treating `-h` otherwise,
but the are a strong minority.

----

I wanted to write a unit test for this.  I looked into `HelpCommandSpec` but did not spot an easy spot that just checked that `--help` was valid syntax so I could update that to `--help` or `-h`.  I haven't used Spek much: *Advice would be welcome*.

### CODE REVIEW

**Comment by binkley** [comment]
BTW ... I find https://github.com/stefanbirkner/system-lambda a nice way to test command-line options
Essentially, it let's me run my Main class with arguments, capture STDOUT and STDERR, and have straight-forward assertions against these outputs.  *Not part of this PR*.  Just food for thought.

**Comment by charleskorn** [comment]
Thanks for the PR @binkley! This looks great. 

> I wanted to write a unit test for this. I looked into HelpCommandSpec but did not spot an easy spot that just checked that --help was valid syntax so I could update that to --help or -h. I haven't used Spek much: Advice would be welcome.

https://github.com/batect/batect/blob/main/app/src/unitTest/kotlin/batect/cli/CommandLineOptionsParserSpec.kt#L220 is probably the place to start.

Once there's a unit test in place, I'd happily merge this.

> Essentially, it let's me run my Main class with arguments, capture STDOUT and STDERR, and have straight-forward assertions against these outputs. Not part of this PR. Just food for thought.

There are a bunch of tests like these - I call them "journey tests" and they're in the https://github.com/batect/batect/blob/main/app/src/journeyTest directory.

**Comment by binkley** [comment]
Looks like I missed shell tab completion!  *PLEASE DON'T MERGE* until I see how to address this

**Comment by binkley** [comment]
I'm not sure I'm using the right test in the right way for **tab completion** of `-h`

**Review by charleskorn — APPROVED** [review]
Looks good to me, thanks @binkley!

**Pull request merged**
