### PR TITLE
Add support for logconfig type

### PR DESCRIPTION
**Pull request by wyvern8**
This is a draft of support for custom logconfig type.

### CODE REVIEW

**Comment by wyvern8** [comment]
Hi @charleskorn this has been tested and resolves the issue running batect in ECS Jenkins slaves.  #299

**Comment by charleskorn** [comment]
Hey @wyvern8, thanks for the PR! Is there any reason why we wouldn't just always use `json-file` as the log driver? (instead of making it configurable)

**Comment by wyvern8** [comment]
Hi @charleskorn, it would make sense to use json-file always in the context of ECS. I just made it configurable in case there are other scenarios where people may want to specify log driver as something else.

**Comment by charleskorn** [comment]
In that case, given it would need to be set for a particular machine (rather than a particular configuration file), I think it would be better if it was configurable as a CLI option or environment variable that batect looks for - what do you think?

**Comment by wyvern8** [comment]
You may be right - is that the convention you intend for container options?  I'll take a closer look soon, but for now this fork has unblocked us at least.

**Comment by charleskorn** [comment]
My convention so far has been:

* things that depend on the configuration of the machine should be CLI options or determined from the machine (eg. what version of Docker it uses determines how we deal with proxies) - the rationale being that a team that shares the same config file might have different setups on their individual computers
* things that depend on the configuration of the tasks or containers should be config file options - the rationale being that we want everyone on a team that shares the same config to have the same experience

Given that the log driver is a machine-specific setting, I'm thinking that the option to configure it should therefore be a CLI option or an environment variable, rather than a config file option.

**Comment by wyvern8** [comment]
Hi Charles, just revisiting this one finally.   A thought - is it possible that users might want to specify logConfigType differently for different containers?  If so, defining per container would be required.

**Comment by charleskorn** [comment]
Hi @wyvern8, I'm not sure, but I imagine not - most people don't even realise you can configure a log driver and I'd expect those that do would do so at the daemon level. Is customising the log driver for different containers something that you need?

**Comment by wyvern8** [comment]
no, not really.  just that logdriver is per container config from a docker perspective, so trying to reconcile that with doing it globally.  I'll take a look at cli option.

**Comment by charleskorn** [comment]
> docker now supports dual logging which probably avoids the original issue we had (but not in ECS yet it seems).. https://docs.docker.com/config/containers/logging/dual-logging/

Unfortunately that's only available with Docker Enterprise, which not many people use.

**Comment by charleskorn** [comment]
I've added setting the log driver to `json-file` by default and this will be part of the next release. If you're interested in adding the ability to customise this, I'd be happy to accept a PR.

**Comment by wyvern8** [comment]
np - sounds like a simpler solution until we actually need customise capability.

**Pull request closed without merging**
